{
 "title": "Linux Server 中文",
 "description": "【中文版本】2020.10.10更新，增加整体资源展示！支持 Grafana6&7，Node Exporter v0.16及以上的版本，优化重要指标展示。包含整体资源展示与资源明细图表：CPU 内存 磁盘 IO 网络等监控指标。https://github.com/starsliao/Prometheus",
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "ds_prometheus", "label": "数据源", "query": "prometheus" },
   {
    "name": "job",
    "label": "JOB",
    "query": {
     "query": "label_values(node_uname_info, job)"
    }
   },
   {
    "name": "hostname",
    "label": "主机名",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\"}, nodename)"
    }
   },
   {
    "name": "node",
    "label": "Instance",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",nodename=~\"$hostname\"},instance)"
    }
   },
   {
    "name": "device",
    "label": "网卡",
    "query": {
     "query": "label_values(node_network_info{instance=~\"$node\",job=~\"$job\",device!~'tap.*|veth.*|br.*|docker.*|virbr.*|lo.*|cni.*|cali*'},device)"
    }
   },
   { "name": "interval", "label": "时间间隔", "query": "5s,30s,1m,2m,3m,5m,10m,30m" },
   {
    "name": "maxmount",
    "label": "最大挂载目录",
    "query": {
     "query": "query_result(topk(1,sort_desc (max(node_filesystem_size_bytes{fstype=~\"ext.?|xfs\",mountpoint!~\".*pods.*\"}) by (mountpoint))))"
    }
   },
   {
    "name": "show_hostname",
    "label": "展示使用的主机名",
    "query": {
     "query": "label_values(node_uname_info{job=~\"$job\",instance=~\"$node\"}, nodename)"
    }
   },
   {
    "name": "total",
    "label": "主机数",
    "query": {
     "query": "query_result(count(node_uname_info{job=~\"$job\"}))"
    }
   },
   {
    "name": "diskdevices",
    "query": "[a-z]+|nvme[0-9]+n[0-9]+|mmcblk[0-9]+"
   }
  ]
 },
 "panels": [
  {
   "title": "资源总览（关联JOB项）当前选中主机：$show_hostname，实例：$node",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "服务器资源总览表【JOB：$job，主机总数：$total】",
   "type": "table-old",
   "description": "分区使用率、磁盘读取、磁盘写入、下载带宽、上传带宽，如果有多个网卡或者多个分区，是采集的使用率最高的网卡或者分区的数值。\n\n连接数：CurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数。",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "sum(time() - node_boot_time_seconds{job=~\"$job\"})by(instance)",
     "legendFormat": "运行时间"
    },
    {
     "expr": "node_memory_MemTotal_bytes{job=~\"$job\"} - 0",
     "legendFormat": "总内存"
    },
    {
     "expr": "count(node_cpu_seconds_total{job=~\"$job\",mode='system'}) by (instance)",
     "legendFormat": "总核数"
    },
    {
     "expr": "node_load5{job=~\"$job\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{job=~\"$job\",mode=\"idle\"}[$interval])) by (instance)) * 100",
     "legendFormat": "CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{job=~\"$job\"} / (node_memory_MemTotal_bytes{job=~\"$job\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "max((node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}) *100/(node_filesystem_avail_bytes {job=~\"$job\",fstype=~\"ext.?|xfs\"}+(node_filesystem_size_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"}-node_filesystem_free_bytes{job=~\"$job\",fstype=~\"ext.?|xfs\"})))by(instance)",
     "legendFormat": "分区使用率"
    },
    {
     "expr": "max(rate(node_disk_read_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大读取"
    },
    {
     "expr": "max(rate(node_disk_written_bytes_total{job=~\"$job\"}[$interval])) by (instance)",
     "legendFormat": "最大写入"
    },
    {
     "expr": "node_netstat_Tcp_CurrEstab{job=~\"$job\"} - 0",
     "legendFormat": "连接数"
    },
    {
     "expr": "node_sockstat_TCP_tw{job=~\"$job\"} - 0",
     "legendFormat": "TIME_WAIT"
    },
    {
     "expr": "max(rate(node_network_receive_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "下载带宽"
    },
    {
     "expr": "max(rate(node_network_transmit_bytes_total{job=~\"$job\"}[$interval])*8) by (instance)",
     "legendFormat": "上传带宽"
    }
   ]
  },
  {
   "title": "磁盘读写速度",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "MBs" } },
   "yaxes": [
    { "format": "MBs" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\",device=~\"sd[a-z]|dm-[0-9]|nvme[0-9]+n[0-9]+\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{device}}_读取速度"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\",device=~\"sd[a-z]|dm-[0-9]|nvme[0-9]+n[0-9]+\"}[1m]) / 1024 / 1024",
     "legendFormat": "{{device}}_写入速度"
    }
   ]
  },
  {
   "title": "服务器磁盘总览表【JOB：$job】",
   "type": "table-old",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "node_uname_info{job=~\"$job\"} - 0",
     "legendFormat": "主机名"
    },
    {
     "expr": "disk_model_name{job=~\"$job\"} - 0 ",
     "legendFormat": "当前设备"
    },
    {
     "expr": "disk_User_Capacity{job=~\"$job\"} - 0",
     "legendFormat": "磁盘总量"
    },
    {
     "expr": "disk_nvme_current_temperature{job=~\"$job\"} - 0 ",
     "legendFormat": "nvme当前温度"
    },
    {
     "expr": "disk_nvme_data_units_read_total{job=~\"$job\"} * 512 - 0 ",
     "legendFormat": "nvme磁盘读取"
    },
    {
     "expr": "disk_nvme_data_units_written_total{job=~\"$job\"} * 512 - 0 ",
     "legendFormat": "nvme磁盘写入"
    },
    {
     "expr": "disk_nvme_disk_power_on_time{job=~\"$job\"} - 0 ",
     "legendFormat": "nvme通电时间"
    },
    {
     "expr": "disk_nvme_percentage_used{job=~\"$job\"} - 0 ",
     "legendFormat": "nvme磁盘已用寿命"
    },
    {
     "expr": "disk_sata_Power_On_Hours{job=~\"$job\"} - 0 ",
     "legendFormat": "sata通电时间"
    },
    {
     "expr": "disk_sata_Reallocated_Sector_Ct{job=~\"$job\"} - 0 ",
     "legendFormat": "sata重映射扇区数"
    },
    {
     "expr": "disk_sata_health{job=~\"$job\"} - 0 ",
     "legendFormat": "sata磁盘健康度"
    },
    {
     "expr": "disk_sata_current_temperature{job=~\"$job\"} - 0 ",
     "legendFormat": "sata磁盘温度"
    }
   ]
  },
  {
   "title": "$node 磁盘使用一览",
   "type": "table-old",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "node_filesystem_size_bytes{job=~\"$job\",instance=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "总量"
    },
    {
     "expr": "node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-0",
     "legendFormat": "可用量"
    },
    {
     "expr": "((node_filesystem_size_bytes{job=~\"$job\",instance=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_avail_bytes {job=~\"$job\",instance=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})  / (node_filesystem_size_bytes{job=~\"$job\",instance=~\"$node\",fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"})) * 100",
     "legendFormat": "利用率"
    },
    {
     "expr": "lvm_data_percent{job=~\"$job\",instance=~\"$node\"}",
     "legendFormat": "lvm利用率"
    }
   ]
  },
  { "title": "主机资源概览：【$show_hostname】", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 } },
  {
   "title": "运行时间",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(time() - node_boot_time_seconds{instance=~\"$node\"})"
    }
   ]
  },
  {
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 7, "x": 2, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "100 - (avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) * 100)",
     "legendFormat": "总CPU使用率"
    },
    {
     "expr": "(1 - (node_memory_MemAvailable_bytes{instance=~\"$node\"} / (node_memory_MemTotal_bytes{instance=~\"$node\"})))* 100",
     "legendFormat": "内存使用率"
    },
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"})*100 /(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint=\"$maxmount\"}))",
     "legendFormat": "最大分区({{mountpoint}})使用率"
    },
    {
     "expr": "(1 - ((node_memory_SwapFree_bytes{instance=~\"$node\"} + 1)/ (node_memory_SwapTotal_bytes{instance=~\"$node\"} + 1))) * 100",
     "legendFormat": "交换分区使用率"
    }
   ]
  },
  {
   "title": "每小时流量$device",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 9, "y": 39 },
   "yaxes": [
    { "format": "bytes", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "increase(node_network_receive_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "increase(node_network_transmit_bytes_total{instance=~\"$node\",device=~\"$device\"}[60m])",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "oom killer 调用",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 39 },
   "targets": [
    {
     "expr": "node_vmstat_oom_kill{job=\"$job\",instance=~'$node',}",
     "legendFormat": "oom killer invocations "
    }
   ]
  },
  {
   "title": "CPU 核数",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(node_cpu_seconds_total{instance=~\"$node\", mode='system'})"
    }
   ]
  },
  {
   "title": "总内存",
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 43 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(node_memory_MemTotal_bytes{instance=~\"$node\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "CPU Basic",
   "type": "graph",
   "description": "Basic CPU info",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=\"system\",instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy System"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='user',instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy User"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode='iowait',instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Iowait"
    },
    {
     "expr": "sum by (instance)(rate(node_cpu_seconds_total{mode=~\".*irq\",instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy IRQs"
    },
    {
     "expr": "sum (rate(node_cpu_seconds_total{mode!='idle',mode!='user',mode!='system',mode!='iowait',mode!='irq',mode!='softirq',instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Busy Other"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~\"$node\",job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle"
    }
   ]
  },
  {
   "title": "系统平均负载",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_load1{instance=~\"$node\"}",
     "legendFormat": "1分钟负载"
    },
    {
     "expr": "node_load5{instance=~\"$node\"}",
     "legendFormat": "5分钟负载"
    },
    {
     "expr": "node_load15{instance=~\"$node\"}",
     "legendFormat": "15分钟负载"
    },
    {
     "expr": " sum(count(node_cpu_seconds_total{instance=~\"$node\", mode='system'}) by (cpu,instance)) by(instance)",
     "legendFormat": "CPU总核数"
    }
   ]
  },
  {
   "title": "Network Traffic Basic",
   "type": "graph",
   "description": "Basic network info per interface",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 45 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "recv {{device}}"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~\"$node\",job=\"$job\"}[$__rate_interval])*8",
     "legendFormat": "trans {{device}} "
    }
   ]
  },
  {
   "title": "CPU使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"system\"}[$interval])) by (instance) *100",
     "legendFormat": "系统使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"user\"}[$interval])) by (instance) *100",
     "legendFormat": "用户使用率"
    },
    {
     "expr": "avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"iowait\"}[$interval])) by (instance) *100",
     "legendFormat": "磁盘IO使用率"
    },
    {
     "expr": "(1 - avg(rate(node_cpu_seconds_total{instance=~\"$node\",mode=\"idle\"}[$interval])) by (instance))*100",
     "legendFormat": "总使用率"
    }
   ]
  },
  {
   "title": "磁盘使用率",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 54 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}) *100/(node_filesystem_avail_bytes {instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}+(node_filesystem_size_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}-node_filesystem_free_bytes{instance=~'$node',fstype=~\"ext.*|xfs\",mountpoint !~\".*pod.*\"}))",
     "legendFormat": "{{mountpoint}}"
    }
   ]
  },
  {
   "title": "DIsk已用寿命",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 54 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "disk_nvme_percentage_used{job=~'$job',instance=~'$node'}*100",
     "legendFormat": "{{device}}"
    }
   ]
  },
  {
   "title": "Memory Basic",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\"} - (node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~\"$node\",job=\"$job\"} + node_memory_Buffers_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~\"$node\",job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~\"$node\",job=\"$job\"} - node_memory_SwapFree_bytes{instance=~\"$node\",job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "I/O Usage Read / Write",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 63 },
   "yaxes": [
    { "format": "Bps", "label": "bytes read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully read bytes"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Successfully written bytes"
    }
   ]
  },
  {
   "title": "Disk IOps",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 75 },
   "yaxes": [
    { "format": "iops", "label": "IO read (-) / write (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\",job=~\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Reads completed"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\",job=~\"$job\",device=~\"$diskdevices\"}[$__rate_interval])",
     "legendFormat": "{{device}} - Writes completed"
    }
   ]
  },
  {
   "title": "打开的文件描述符(左 )/每秒上下文切换次数(右)",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 75 },
   "yaxes": [
    { "format": "short", "label": "使用的文件描述符" }
   ],
   "targets": [
    {
     "expr": "node_filefd_allocated{instance=~\"$node\"}",
     "legendFormat": "使用的文件描述符"
    },
    {
     "expr": "rate(node_context_switches_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "每秒上下文切换次数"
    }
   ]
  },
  {
   "title": "I/O Utilization",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 87 },
   "yaxes": [
    { "format": "percentunit", "label": "%util" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\",job=\"$job\",device=~\"$diskdevices\"} [$__rate_interval])",
     "legendFormat": "{{device}}"
    }
   ]
  },
  { "title": "CPU / Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 99 } },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 100 },
   "yaxes": [
    { "format": "short", "label": "percentage" }
   ],
   "targets": [
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode=\"system\",instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "System - Processes executing in kernel mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='user',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "User - Normal processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='nice',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Nice - Niced processes executing in user mode"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='idle',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Idle - Waiting for something to happen"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='iowait',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Iowait - Waiting for I/O to complete"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='irq',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Irq - Servicing interrupts"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='softirq',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Softirq - Servicing softirqs"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='steal',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Steal - Time spent in other operating systems when running in a virtualized environment"
    },
    {
     "expr": "sum by (mode)(rate(node_cpu_seconds_total{mode='guest',instance=~'$node',job=\"$job\"}[$__rate_interval])) * 100",
     "legendFormat": "Guest - Time spent running a virtual CPU for a guest operating system"
    }
   ]
  },
  {
   "title": "内存信息",
   "type": "graph",
   "description": "Basic memory usage",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 100 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "RAM Total"
    },
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$node',job=\"$job\"} - node_memory_MemFree_bytes{instance=~'$node',job=\"$job\"} - (node_memory_Cached_bytes{instance=~'$node',job=\"$job\"} + node_memory_Buffers_bytes{instance=~'$node',job=\"$job\"})",
     "legendFormat": "RAM Used"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node',job=\"$job\"} + node_memory_Buffers_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "RAM Cache + Buffer"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "RAM Free"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node',job=\"$job\"} - node_memory_SwapFree_bytes{instance=~'$node',job=\"$job\"})",
     "legendFormat": "SWAP Used"
    }
   ]
  },
  {
   "title": "内存堆栈",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 100 },
   "yaxes": [
    { "format": "bytes", "label": "bytes" }
   ],
   "targets": [
    {
     "expr": "node_memory_MemTotal_bytes{instance=~'$node',job=\"$job\"} - node_memory_MemFree_bytes{instance=~'$node',job=\"$job\"} - node_memory_Buffers_bytes{instance=~'$node',job=\"$job\"} - node_memory_Cached_bytes{instance=~'$node',job=\"$job\"} - node_memory_Slab_bytes{instance=~'$node',job=\"$job\"} - node_memory_PageTables_bytes{instance=~'$node',job=\"$job\"} - node_memory_SwapCached_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Apps - Memory used by user-space applications"
    },
    {
     "expr": "node_memory_PageTables_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "PageTables - Memory used to map between virtual and physical memory addresses"
    },
    {
     "expr": "node_memory_SwapCached_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "SwapCache - Memory that keeps track of pages that have been fetched from swap but not yet been modified"
    },
    {
     "expr": "node_memory_Slab_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Slab - Memory used by the kernel to cache data structures for its own use (caches like inode, dentry, etc)"
    },
    {
     "expr": "node_memory_Cached_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Cache - Parked file data (file content) cache"
    },
    {
     "expr": "node_memory_Buffers_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Buffers - Block device (e.g. harddisk) cache"
    },
    {
     "expr": "node_memory_MemFree_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Unused - Free memory unassigned"
    },
    {
     "expr": "(node_memory_SwapTotal_bytes{instance=~'$node',job=\"$job\"} - node_memory_SwapFree_bytes{instance=~'$node',job=\"$job\"})",
     "legendFormat": "Swap - Swap space used"
    },
    {
     "expr": "node_memory_HardwareCorrupted_bytes{instance=~'$node',job=\"$job\"}",
     "legendFormat": "Hardware Corrupted - Amount of RAM that the kernel identified as corrupted / not working"
    }
   ]
  },
  { "title": "网络、磁盘详情", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 107 } },
  {
   "title": "磁盘读写速率（IOPS）",
   "type": "graph",
   "description": "Reads completed: 每个磁盘分区每秒读完成次数\n\nWrites completed: 每个磁盘分区每秒写完成次数\n\nIO now 每个磁盘分区每秒正在处理的输入/输出请求数",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 108 },
   "yaxes": [
    { "format": "iops", "label": "读取（-）/写入（+）I/O ops/sec" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每次IO读写的耗时（参考：小于100ms）(beta)",
   "type": "graph",
   "description": "Read time seconds 每个磁盘分区读操作花费的秒数\n\nWrite time seconds 每个磁盘分区写操作花费的秒数\n\nIO time seconds 每个磁盘分区输入/输出操作花费的秒数\n\nIO time weighted seconds每个磁盘分区输入/输出操作花费的加权秒数",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 108 },
   "yaxes": [
    { "format": "s", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_reads_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_write_time_seconds_total{instance=~\"$node\"}[$interval]) / rate(node_disk_writes_completed_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": "每秒网络带宽使用$device",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 108 },
   "yaxes": [
    { "format": "bps", "label": "上传（-）/下载（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_in下载"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{instance=~'$node',device=~\"$device\"}[$interval])*8",
     "legendFormat": "{{device}}_out上传"
    }
   ]
  },
  {
   "title": "每1秒内I/O操作耗时占比",
   "type": "graph",
   "description": "每一秒钟的自然时间内，花费在I/O上的耗时。（wall-clock time）\n\nnode_disk_io_time_seconds_total：\n磁盘花费在输入/输出操作上的秒数。该值为累加值。（Milliseconds Spent Doing I/Os）\n\nrate(node_disk_io_time_seconds_total[1m])：\n计算每秒的速率：(last值-last前一个值)/时间戳差值，即：1秒钟内磁盘花费在I/O操作的时间占比。",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 117 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_io_time_seconds_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_每秒I/O操作%"
    }
   ]
  },
  {
   "title": "每秒磁盘读写容量",
   "type": "graph",
   "description": "Read bytes 每个磁盘分区每秒读取的比特数\nWritten bytes 每个磁盘分区每秒写入的比特数",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 117 },
   "yaxes": [
    { "format": "Bps", "label": "读取（-）/写入（+）" }
   ],
   "targets": [
    {
     "expr": "rate(node_disk_read_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_读取"
    },
    {
     "expr": "rate(node_disk_written_bytes_total{instance=~\"$node\"}[$interval])",
     "legendFormat": "{{device}}_写入"
    }
   ]
  },
  {
   "title": " 网络流量",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 117 },
   "yaxes": [
    { "format": "bps", "label": "bits out (-) / in (+)" }
   ],
   "targets": [
    {
     "expr": "rate(node_network_receive_bytes_total{device=~\"$device\",job=\"$job\",instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - 接收"
    },
    {
     "expr": "rate(node_network_transmit_bytes_total{device=~\"$device\",job=\"$job\",instance=\"$node\"}[$__rate_interval])*8",
     "legendFormat": "{{device}} - 发送"
    }
   ]
  },
  {
   "title": "网络Socket连接信息",
   "type": "graph",
   "description": "Sockets_used - 已使用的所有协议套接字总量\n\nCurrEstab - 当前状态为 ESTABLISHED 或 CLOSE-WAIT 的 TCP 连接数\n\nTCP_alloc - 已分配（已建立、已申请到sk_buff）的TCP套接字数量\n\nTCP_tw - 等待关闭的TCP连接数\n\nUDP_inuse - 正在使用的 UDP 套接字数量\n\nRetransSegs - TCP 重传报文数\n\nOutSegs - TCP 发送的报文数\n\nInSegs - TCP 接收的报文数",
   "gridPos": { "h": 8, "w": 16, "x": 0, "y": 125 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "node_netstat_Tcp_CurrEstab{instance=~'$node'}",
     "legendFormat": "CurrEstab"
    },
    {
     "expr": "node_sockstat_TCP_tw{instance=~'$node'}",
     "legendFormat": "TCP_tw"
    },
    {
     "expr": "node_sockstat_sockets_used{instance=~'$node'}",
     "legendFormat": "Sockets_used"
    },
    {
     "expr": "node_sockstat_UDP_inuse{instance=~'$node'}",
     "legendFormat": "UDP_inuse"
    },
    {
     "expr": "node_sockstat_TCP_alloc{instance=~'$node'}",
     "legendFormat": "TCP_alloc"
    },
    {
     "expr": "rate(node_netstat_Tcp_InSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_InSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_OutSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_OutSegs"
    },
    {
     "expr": "rate(node_netstat_Tcp_RetransSegs{instance=~'$node'}[$interval])",
     "legendFormat": "Tcp_RetransSegs"
    }
   ]
  },
  { "title": "硬件温度监控", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 133 } },
  {
   "title": "CPU硬件温度监控（avg）",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 134 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "expr": "avg(node_hwmon_temp_celsius{instance=~'$node',job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} temp"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_alarm_celsius{instance=~'$node',job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} Critical Alarm"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_celsius{instance=~'$node',job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} Critical"
    },
    {
     "expr": "avg(node_hwmon_temp_crit_hyst_celsius{instance=~'$node',job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} Critical Historical"
    },
    {
     "expr": "avg(node_hwmon_temp_max_celsius{instance=~'$node',job=\"$job\"})",
     "legendFormat": "{{ chip }} {{ sensor }} Max"
    }
   ]
  }
 ]
}